define([], function() {
  return {
    "SearchQuerySettingsGroupName": "Search query configuration",
    "SearchSettingsGroupName": "Search settings",
    "RefinersSettingsGroupName": "Search Refiners settings",
    "SearchQueryKeywordsFieldLabel": "Search query keywords",
    "QueryTemplateFieldLabel": "Query template",
    "SelectedPropertiesFieldLabel": "Selected Properties",
    "LoadingMessage": "Results are loading, please wait...",
    "EnableLocalizationLabel": "Enable taxonomy values localization for refiners and results",
    "EnableLocalizationOnLabel": "Localization enabled",
    "EnableLocalizationOffLabel": "Localization disabled",
    "NoResultMessage": "No results to display",
    "FilterPanelTitle": "Available filters",
    "FilterResultsButtonLabel": "Filters",
    "SelectedFiltersLabel": "Selected filters",
    "SearchResultsLabel": "Search results",
    "RemoveAllFiltersLabel": "Remove all filters",
    "UsePaginationWebPartLabel": "Connect to a search pagination Web Part",
    "ShowResultsCountLabel": "Show results count",
    "ShowBlankLabel": "Show blank if no result",
    "ShowBlankEditInfoMessage": "No result returned for this query. This Web Part will remain blank in display mode according to parameters.",
    "NoFilterConfiguredLabel": "No filter configured",
    "SearchQueryPlaceHolderText": "Search query in KQL format",
    "EmptyFieldErrorMessage": "This field cannot be empty",
    "PlaceHolderEditLabel": "Edit",
    "PlaceHolderConfigureBtnLabel": "Configure",
    "PlaceHolderIconText": "Search Results Web Part",
    "PlaceHolderDescription": "This component displays search results with paging",
    "ResultSourceIdLabel": "Result Source Identifier",
    "InvalidResultSourceIdMessage": "Invalid identifier",
    "InvalidNumberIntervalMessage": "Between 1 and 500",
    "EnableQueryRulesLabel": "Enable query rules",
    "IncludeOneDriveResultsLabel": "Include personal OneDrive results",
    "StylingSettingsGroupName": "Styling options",
    "SelectedPropertiesFieldDescription": "Specifies the properties to retrieve from the search results.",
    "SearchQueryKeywordsFieldDescription": "Use pre-defined search query keywords to retrieve a static set of results.",
    "CountMessageLong": "<b>{0}</b> results for '<em>{1}</em>'",
    "CountMessageShort": "<b>{0}</b> results",
    "CancelButtonText": "Cancel",
    "DialogButtonLabel": "Edit template",
    "DialogButtonText": "Edit template",
    "DialogTitle": "Edit results template",
    "SaveButtonText": "Save",
    "SimpleListLayoutOption": "Simple list",
    "DetailsListLayoutOption": "Details list",
    "TilesLayoutOption": "Tiles",
    "CustomLayoutOption": "Custom",
    "DebugLayoutOption": "Debug",
    "SliderLayoutOption": "Carousel",
    "PeopleLayoutOption": "People",
    "ResultsLayoutLabel": "Results layout",
    "TemplateUrlFieldLabel": "Use an external template URL",
    "TemplateUrlPlaceholder": "https://myfile.html",
    "ErrorTemplateExtension": "The template must be a valid .htm or .html file",
    "ErrorTemplateResolve": "Unable to resolve the specified template. Error details: '{0}'",
    "HandlebarsHelpersDescription": "Enable functions from moment and handlebars helpers. See https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/README.md#available-tokens for more information.",
    "PromotedResultsLabel": "Promoted result(s)",
    "PanelCloseButtonAria": "Close",
    "UseRefinersWebPartLabel": "Use search refiners",
    "UseSearchBoxWebPartLabel": "Use search box",
    "UseRefinersFromComponentLabel": "Use refiners from this component",
    "UsePaginationFromComponentLabel": "Use pagination from this component",
    "RefinementFilters": "Refinement filters",
    "customTemplateFieldsLabel": "Custom template field values",
    "customTemplateFieldsPanelHeader": "Custom template field values",
    "customTemplateFieldsConfigureButtonLabel": "Configure",
    "customTemplateFieldTitleLabel": "Field Name",
    "customTemplateFieldPropertyLabel": "Search Property",
    "Sort": {
        "SortableFieldsPropertyPaneField": "Sortable properties",
        "SortableFieldsDescription": "Specifies sortable properties that users can use in the UI. Only one property can be used at a time for sorting and will override the search order specified in the WP if exists.",
        "SortPropertyPaneFieldLabel": "Sort order",
        "SortListDescription": "Specify the sort order for the search results. This will only  applied when no manual filters have been set (i.e. sortable fields)",
        "SortDirectionAscendingLabel": "Ascending",
        "SortDirectionDescendingLabel": "Descending",
        "SortErrorMessage": "Invalid search property (Check if the managed property is sortable).",
        "SortPanelSortFieldLabel": "Sort on field",
        "SortPanelSortFieldAria": "Sort by",
        "SortPanelSortFieldPlaceHolder": "Sort by",
        "SortPanelSortDirectionLabel": "Sort Direction",
        "SortableFieldManagedPropertyField": "Sort managed property",
        "SortableFieldDisplayValueField": "Field name to display",
        "EditSortableFieldsLabel": "Edit sortable fields",
        "EditSortLabel": "Edit sort order",
        "SortInvalidSortableFieldMessage": "This property is not sortable"
    },
    "Synonyms": {
        "EditSynonymLabel": "Edit synonyms",
        "SynonymListDescription": "Specify all the synonyms that will be used when searching. Each term a search will be enhanced with all the associated synonyms when the query is sent to the server. If a synonym contains more than one word, it has to be wrapped in double quotes.",
        "SynonymPropertyPanelFieldLabel": "Configure synonyms",
        "SynonymListTerm": "Term",
        "SynonymListSynonyms": "Synonyms",
        "SynonymIsTwoWays": "Two-ways?",
        "SynonymListSynonymsExemple": "Laptop, \"Desktop with monitor\"",
        "SynonymListTermExemple": "Computer"
    },
    "TermNotFound": "(Term with ID '{0}' not found)",
    "UseDefaultSearchQueryKeywordsFieldLabel": "Use a default search query",
    "DefaultSearchQueryKeywordsFieldLabel": "Default search query",
    "DefaultSearchQueryKeywordsFieldDescription": "This query will be used when the data source value is still empty.",
    "ResultTypes": {
        "ResultTypeslabel": "Result Types",
        "ResultTypesDescription": "Add here the display templates to use for result items according to one ore more conditions. Conditions are evaluated in the configured order and external template takes precedence over inline templates. Make sure the managed properties you use are present in the 'Selected Properties' of this Web Part.",
        "InlineTemplateContentLabel": "Inline template",
        "EditResultTypesLabel": "Edit Result Types",
        "ConditionPropertyLabel": "Managed Property",
        "ConditionValueLabel": "Condition Value",
        "CondtionOperatorValue": "Operator",
        "ExternalUrlLabel": "External Template Url",
        "EqualOperator": "Equals",
        "NotEqualOperator": "Not equals",
        "ContainsOperator": "Contains",
        "StartsWithOperator": "Starts with",
        "NotNullOperator": "Is not null",
        "GreaterOrEqualOperator": "Greater or equal",
        "GreaterThanOperator": "Greater than",
        "LessOrEqualOperator": "Less or equal",
        "LessThanOperator": "Less than"
    },
    "QueryCultureLabel": "Language of search request",
    "QueryCultureUseUiLanguageLabel": "Use interface language",
    "TemplateParameters": {
        "TemplateParametersGroupName": "Template options",
        "EnableItemPreview": "Enable result preview",
        "ShowFileIcon": "Show file icon",
        "ManageDetailsListColumnDescription": "Add, update or remove columns for the details list layout. You can use either the managed property value directly without any transformation or use an Handlebars expression in the value field. HTML is supported for all fields as well.",
        "ManageDetailsListColumnLabel": "Manage columns",
        "ManageTilesFieldsLabel": "Manage card fields",
        "ManagePeopleFieldsLabel": "Manage persona fields",
        "ManagePeopleFieldsPanelDescriptionLabel": "Here you can map each field values with the corresponding persona placeholders. You can use either the managed property value directly without any transformation or use an Handlebars expression in the value field.",
        "ManageTilesFieldsPanelDescriptionLabel": "Here you can map each field values with the corresponding card placeholders. You can use either the managed property value directly without any transformation or use an Handlebars expression in the value field. Also, when indicated, you can also inject your own HTML code in some fields.",
        "PlaceholderNameFieldLabel": "Name",
        "PlaceholderValueFieldLabel": "Value",
        "ValueColumnLabel": "Column value",
        "DisplayNameColumnLabel": "Column display name",
        "UseHandlebarsExpressionLabel": "Use Handlebars expression",
        "MinimumWidthColumnLabel": "Minimum width (px)",
        "MaximumWidthColumnLabel": "Maximum width (px)",
        "SortableColumnLabel": "Sortable",
        "ResizableColumnLabel": "Resizable",
        "MultilineColumnLabel": "Multiline",
        "LinkToItemColumnLabel": "Link to item",
        "SupportHTMLColumnLabel": "Allow HTML",
        "CompactModeLabel": "Compact mode",
        "SliderAutoPlayDuration": "Advance element every (seconds)",
        "SliderAutoPlay": "Auto play",
        "SliderPauseAutoPlayOnHover": "Pause on hover",
        "SliderGroupCells": "Number of elements to group together in slides",
        "SliderShowPageDots": "Show page dots",
        "SliderWrapAround": "Infinite scrolling",
        "PersonaSizeOptionsLabel": "Picture size",
        "PersonaSizeExtraSmall": "Extra small",
        "PersonaSizeSmall": "Small",
        "PersonaSizeRegular": "Regular",
        "PersonaSizeLarge": "Large",
        "PersonaSizeExtraLarge": "Extra large",
    },
    "ManagedPropertiesListPlaceHolder": "Select or add a managed property",
    "QueryModifier": {
        "FieldLbl": "Search query modifiers",
        "ConfigureBtn": "Configure",
        "PanelHeader": "Configure search query modifiers",
        "PanelDescription": "You can associate only one query modifier to a search result Web Part",
        "EnableColumnLbl": "Enabled",
        "DisplayNameColumnLbl": "Name",
        "DescriptionColumnLbl": "Description",
        "SelectedQueryModifierLbl": "Selected query modifier: '{0}'"
    },
    "Paging": {
        "PagingOptionsGroupName": "Paging settings",
        "ItemsCountPerPageFieldName": "Number of items per page",
        "PagingRangeFieldName": "Number of pages to display in range",
        "ShowPagingFieldName": "Show paging",
        "HidePageNumbersFieldName": "Hide page numbers",
        "HideNavigationFieldName": "Hide navigation buttons (prev page, next page)",
        "HideFirstLastPagesFieldName": "Hide first/last navigation buttons",
        "HideDisabledFieldName": "Hide navigation buttons (prev, next, first, last) if they are disabled.",
    },
    "SearchInputPlaceholder": "Enter your search terms...",
    "SearchBoxQuerySuggestionsSettings": "Search query suggestions settings",
    "SearchBoxEnableQuerySuggestions": "Enable query suggestions",
    "SearchBoxNewPage": "Search box options",
    "SearchBoxSearchInNewPageLabel": "Send the query to a new page",
    "SearchBoxPageUrlLabel": "Page URL",
    "SearchBoxUrlErrorMessage": "Please provide a valid URL.",
    "SearchBoxQuerySettings": "Default search query settings",
    "SearchBoxSameTabOpenBehavior": "Use the current tab",
    "SearchBoxNewTabOpenBehavior": "Open in a new tab",
    "SearchBoxPageOpenBehaviorLabel": "Opening behavior",
    "SearchBoxQueryPathBehaviorLabel": "Method",
    "SearchBoxUrlFragmentQueryPathBehavior": "URL fragment",
    "SearchBoxQueryStringQueryPathBehavior": "Query parameter",
    "SearchBoxQueryStringParameterName": "Query parameter name",
    "SearchBoxQueryParameterNotEmpty": "Please provide a value for the parameter",
    "SearchBoxQueryNlpSettings": "Search query enhancement",
    "SearchBoxQueryNlpSettingsDescription": "Use this service to enhance the search query by detecting user intents and get more relevant search keywords using Microsoft LUIS.",
    "SearchBoxUserQueryNlpLabel": "Use Natural Language Processing service",
    "SearchBoxServiceUrlLabel": "Service URL",
    "SearchBoxServiceUrlDescription": "Notice: make sure the server allows cross-origin calls from this domain ('{0}') in CORS settings.",
    "SearchBoxServiceUrlErrorMessage": "Please specify a valid URL",
    "SearchBoxUseDebugModeLabel": "Enable debug mode",
    "SearchBoxUseStagingEndpoint": "Use LUIS staging endpoint",
    "UrlNotResolvedErrorMessage": "URL '{0}' can't be resolved. Error: '{1}'.",
    "SearchBoxPlaceholderTextLabel": "Placeholder text in search box",
    "CancelButtonText": "Cancel",
    "DialogButtonLabel": "Edit template",
    "DialogButtonText": "Edit template",
    "SaveButtonText": "Save",
    "DynamicData": {
      "UseDynamicDataSourceLabel": "Use a dynamic data  source",
      "SearchQueryPropertyLabel": "Search query",
      "RawInputValuePropertyLabel": "Raw user search query",
      "EnhancedQueryPropertyLabel": "NLP enhanced search query"
    },
    "DebugPanel": {
      "HeaderLabel": "NLP debug informations",
      "DetectedLanguageLabel": "Language detected",
      "RecognizedEntitiesLabel": "Recognized entities",
      "TopScoringIntentNameLabel": "Top scoring entity",
      "TopScoringIntentScoreLabel": "Top scoring entity confidence",
      "EnhancedQueryLabel": "Enhanced search query",
      "AlteredQueryLabel": "Corrected query"
    },
    "SuggestionProviders": {
      "EditSuggestionProvidersLabel": "Configure Suggestions",
      "SuggestionProvidersLabel": "Suggestion Providers",
      "SuggestionProvidersDescription": "Enable or disable individual suggestion providers.",
      "EnabledPropertyLabel": "Active",
      "ProviderNamePropertyLabel": "Name",
      "ProviderDescriptionPropertyLabel": "Description",
      "InlineTemplateContentLabel": "Inline Template",
      "ExternalUrlLabel": "External Template Url",
      "InlineTemplateEditPanelTitle": "Edit suggestion template",
      "DefaultSuggestionGroupName": "Recommended",
      "SharePointSuggestionGroupName": "Others have search for",
    },
    "RefinersConfigurationGroupName": "Refiner settings",
    "ShowBlankLabel": "Show blank if no result",
    "StylingSettingsGroupName": "Styling options",
    "AppliedRefinersLabel": "Applied refiners",
    "PlaceHolderEditLabel": "Edit",
    "PlaceHolderConfigureBtnLabel": "Configure",
    "PlaceHolderIconText": "Search Refiners Web Part",
    "PlaceHolderDescription": "This component displays search refiners",
    "NoFilterConfiguredLabel": "No filter available",
    "RemoveAllFiltersLabel": "Remove all filters",
    "ShowBlankEditInfoMessage": "No filter to display. This Web Part will remain blank in display mode according to parameters.",
    "RefinersConfiguration": "Refiners configuration",
    "SearchResultsLabel": "Search results",
    "SearchQueryLabel": "Search query",
    "FilterResultsButtonLabel": "Filters",
    "SelectedFiltersLabel": "Selected filters:",
    "RefinerLayoutLabel": "Filters layout",
    "ConnectToSearchResultsLabel": "Connect to search results Web Part",
    "Refiners": {
      "RefinersFieldLabel": "Refiners",
      "RefinerManagedPropertyField": "Filter managed property",
      "RefinerDisplayValueField": "Filter name to display",
      "RefinerTemplateField": "Refiner template",
      "RefinersFieldDescription": "Specifies managed properties used as refiners. If there are no values for a filter property, it won't appear in the panel.",
      "EditRefinersLabel": "Edit refiners",
      "AvailableRefinersLabel": "Available refiners",
      "ApplyFiltersLabel": "Apply",
      "ClearFiltersLabel": "Clear",
      "ShowExpanded": "Expand filter by default",
      "showValueFilter": "Show filter for refinement values",
      "Templates": {
        "RefinementItemTemplateLabel": "Default refinement item",
        "MutliValueRefinementItemTemplateLabel": "Multi-value refinement item",
        "PersonaRefinementItemLabel": "Persona",
        "DateRangeRefinementItemLabel": "Date range",
        "FixedDateRangeRefinementItemLabel": "Date range (fixed intervals)",
        "FileTypeRefinementItemTemplateLabel": "File type",
        "FileTypeMutliValueRefinementItemTemplateLabel": "Multiple file type",
        "ContainerTreeRefinementItemTemplateLabel": "Container Tree",
        "DateFromLabel": "From",
        "DateTolabel": "To",
        "DatePickerStrings": {
          "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
          "shortMonths": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
          "days": ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
          "shortDays": ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
          "goToToday": 'Go to today',
          "prevMonthAriaLabel": 'Go to previous month',
          "nextMonthAriaLabel": 'Go to next month',
          "prevYearAriaLabel": 'Go to previous year',
          "nextYearAriaLabel": 'Go to next year',
          "closeButtonAriaLabel": 'Close date picker',
          "isRequiredErrorMessage": 'Start date is required.',
          "invalidInputErrorMessage": 'Invalid date format.'
        },
        "DateIntervalStrings": {
          "AnyTime": "Any time",
          "PastDay": "Past 24 hours",
          "PastWeek": "Past week",
          "PastMonth": "Past month",
          "Past3Months": "Past 3 months",
          "PastYear": "Past year",
          "Older": "Older than a year"
        },
        "RefinerSortTypeLabel": "Refiner sort type",
        "RefinerSortTypeAlphabetical": "Alphabetical",
        "RefinerSortTypeByNumberOfResults": "By number of results",
        "RefinerSortTypeSortOrderLabel": "Sort order",
        "RefinerSortTypeSortDirectionAscending": "Ascending",
        "RefinerSortTypeSortDirectionDescending": "Descending"
      }
    }
  }
});